/* tslint:disable */
/* eslint-disable */
/**
 * Data Modelling Job API
 * REST API used with the Data Modelling framework to schedule jobs
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { GetJobResultResponse } from '../models';
// @ts-ignore
import { StartJobResponse } from '../models';
// @ts-ignore
import { StatusJobResponse } from '../models';
/**
 * DMJobsApi - axios parameter creator
 * @export
 */
export const DMJobsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Result
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobResult: async (jobUid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobUid' is not null or undefined
            assertParamExists('jobResult', 'jobUid', jobUid)
            const localVarPath = `/{job_uid}/result`
                .replace(`{${"job_uid"}}`, encodeURIComponent(String(jobUid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthorizationCodeBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthorizationCodeBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Status
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobStatus: async (jobUid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobUid' is not null or undefined
            assertParamExists('jobStatus', 'jobUid', jobUid)
            const localVarPath = `/{job_uid}`
                .replace(`{${"job_uid"}}`, encodeURIComponent(String(jobUid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthorizationCodeBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthorizationCodeBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeJob: async (jobUid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobUid' is not null or undefined
            assertParamExists('removeJob', 'jobUid', jobUid)
            const localVarPath = `/{job_uid}`
                .replace(`{${"job_uid"}}`, encodeURIComponent(String(jobUid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthorizationCodeBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthorizationCodeBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start
         * @param {string} jobDmssId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startJob: async (jobDmssId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobDmssId' is not null or undefined
            assertParamExists('startJob', 'jobDmssId', jobDmssId)
            const localVarPath = `/{job_dmss_id}`
                .replace(`{${"job_dmss_id"}}`, encodeURIComponent(String(jobDmssId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2AuthorizationCodeBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2AuthorizationCodeBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DMJobsApi - functional programming interface
 * @export
 */
export const DMJobsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DMJobsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Result
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobResult(jobUid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetJobResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jobResult(jobUid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Status
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobStatus(jobUid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jobStatus(jobUid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Remove
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeJob(jobUid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeJob(jobUid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Start
         * @param {string} jobDmssId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startJob(jobDmssId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startJob(jobDmssId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DMJobsApi - factory interface
 * @export
 */
export const DMJobsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DMJobsApiFp(configuration)
    return {
        /**
         * 
         * @summary Result
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobResult(jobUid: string, options?: any): AxiosPromise<GetJobResultResponse> {
            return localVarFp.jobResult(jobUid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Status
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobStatus(jobUid: string, options?: any): AxiosPromise<StatusJobResponse> {
            return localVarFp.jobStatus(jobUid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove
         * @param {string} jobUid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeJob(jobUid: string, options?: any): AxiosPromise<any> {
            return localVarFp.removeJob(jobUid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start
         * @param {string} jobDmssId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startJob(jobDmssId: string, options?: any): AxiosPromise<StartJobResponse> {
            return localVarFp.startJob(jobDmssId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for jobResult operation in DMJobsApi.
 * @export
 * @interface DMJobsApiJobResultRequest
 */
export interface DMJobsApiJobResultRequest {
    /**
     * 
     * @type {string}
     * @memberof DMJobsApiJobResult
     */
    readonly jobUid: string
}

/**
 * Request parameters for jobStatus operation in DMJobsApi.
 * @export
 * @interface DMJobsApiJobStatusRequest
 */
export interface DMJobsApiJobStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof DMJobsApiJobStatus
     */
    readonly jobUid: string
}

/**
 * Request parameters for removeJob operation in DMJobsApi.
 * @export
 * @interface DMJobsApiRemoveJobRequest
 */
export interface DMJobsApiRemoveJobRequest {
    /**
     * 
     * @type {string}
     * @memberof DMJobsApiRemoveJob
     */
    readonly jobUid: string
}

/**
 * Request parameters for startJob operation in DMJobsApi.
 * @export
 * @interface DMJobsApiStartJobRequest
 */
export interface DMJobsApiStartJobRequest {
    /**
     * 
     * @type {string}
     * @memberof DMJobsApiStartJob
     */
    readonly jobDmssId: string
}

/**
 * DMJobsApi - object-oriented interface
 * @export
 * @class DMJobsApi
 * @extends {BaseAPI}
 */
export class DMJobsApi extends BaseAPI {
    /**
     * 
     * @summary Result
     * @param {DMJobsApiJobResultRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DMJobsApi
     */
    public jobResult(requestParameters: DMJobsApiJobResultRequest, options?: any) {
        return DMJobsApiFp(this.configuration).jobResult(requestParameters.jobUid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Status
     * @param {DMJobsApiJobStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DMJobsApi
     */
    public jobStatus(requestParameters: DMJobsApiJobStatusRequest, options?: any) {
        return DMJobsApiFp(this.configuration).jobStatus(requestParameters.jobUid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove
     * @param {DMJobsApiRemoveJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DMJobsApi
     */
    public removeJob(requestParameters: DMJobsApiRemoveJobRequest, options?: any) {
        return DMJobsApiFp(this.configuration).removeJob(requestParameters.jobUid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start
     * @param {DMJobsApiStartJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DMJobsApi
     */
    public startJob(requestParameters: DMJobsApiStartJobRequest, options?: any) {
        return DMJobsApiFp(this.configuration).startJob(requestParameters.jobDmssId, options).then((request) => request(this.axios, this.basePath));
    }
}
