/* tslint:disable */
/* eslint-disable */
/**
 * Data Modelling Job API
 * REST API used with the Data Modelling framework to schedule jobs
 *
 * The version of the OpenAPI document: 1.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { JobStatus } from './job-status';

/**
 * 
 * @export
 * @interface StartJobResponse
 */
export interface StartJobResponse {
    /**
     * 
     * @type {string}
     * @memberof StartJobResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof StartJobResponse
     */
    'uid': string;
    /**
     * 
     * @type {JobStatus}
     * @memberof StartJobResponse
     */
    'status': JobStatus;
}



