import {
  add,
  chevron_right,
  copy,
  delete_to_trash,
  desktop_mac,
  drag_handle,
  edit,
  type IconData,
  image,
  list,
  phone,
  table_chart,
  tablet_android,
  text_field,
  view_module,
  visibility,
} from '@equinor/eds-icons'

/** Maps block icon names to EDS icon data objects used by `<Icon />`. */
export const ICONS: Record<string, IconData> = {
  view_module,
  text_field,
  image,
  table_chart,
  list,
  add,
  edit,
  visibility,
  drag_handle,
  delete_to_trash,
  copy,
  chevron_right,
  desktop_mac,
  tablet_android,
  phone,
}
